# Generated by Django 5.2.7 on 2025-10-30 10:15

import django.db.models.deletion
import main.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='DesignRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('plan_image', models.ImageField(upload_to='plan_img/', validators=[main.models.validate_image_extension_and_size])),
                ('status', models.CharField(choices=[('new', 'Новая'), ('in_progress', 'Принято'), ('complited', 'Выполнено')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('design_image', models.ImageField(blank=True, null=True, upload_to='design_img/', validators=[main.models.validate_image_extension_and_size])),
                ('admin_comment', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Заявка на дизайн',
                'verbose_name_plural': 'Зявки на дизайн',
                'ordering': ['-created_at'],
            },
        ),
    ]
