# Generated by Django 5.2.7 on 2025-11-01 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='designrequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'Заявка на дизайн', 'verbose_name_plural': 'Заявки на дизайн'},
        ),
        migrations.AlterField(
            model_name='designrequest',
            name='status',
            field=models.CharField(choices=[('new', 'Новая'), ('in_progress', 'Принято'), ('completed', 'Выполнено')], default='new', max_length=20),
        ),
    ]
