# Generated by Django 5.2.7 on 2025-11-05 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_designrequest_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designrequest',
            name='status',
            field=models.CharField(choices=[('new', 'Новая'), ('in_progress', 'Принято'), ('complited', 'Выполнено')], default='new', max_length=20),
        ),
    ]
